CREATE TABLE IF NOT EXISTS reactroles(guildId INTEGER NOT NULL, channelId INTEGER, messageId INTEGER NOT NULL, emote VARCHAR(255) NOT NULL, roleId INTEGER NOT NULL, CONSTRAINT pk PRIMARY KEY(guildId, channelId, messageId, emote));

CREATE TABLE IF NOT EXISTS modlogs(id INTEGER NOT NULL AUTO_INCREMENT, guildId INTEGER, memberId INTEGER NOT NULL, requesterId INTEGER NOT NULL, memberName TEXT, requesterName TEXT, action TEXT, reason TEXT, date DATETIME, CONSTRAINT pk PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS createdprivatevcs(guildId INTEGER NOT NULL, channelId INTEGER NOT NULL, CONSTRAINT pk PRIMARY KEY (guildId, channelId));

CREATE TABLE IF NOT EXISTS musicutil(guildId INTEGER NOT NULL, CONSTRAINT pk PRIMARY KEY (guildId), channelId INTEGER, volume INTEGER NOT NULL DEFAULT 10);

CREATE TABLE IF NOT EXISTS statschannels(guildId INTEGER NOT NULL, CONSTRAINT pk PRIMARY KEY (guildId), categoryId INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS botutil(guildId INTEGER, CONSTRAINT pk PRIMARY KEY (guildId), syschannelId INTEGER, prefix TEXT NOT NULL DEFAULT '-');

CREATE TABLE IF NOT EXISTS vplancurrent(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), targetDate DATE, classEntrys INTEGER);

CREATE TABLE IF NOT EXISTS vplannext(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), targetDate DATE, classEntrys INTEGER);

CREATE TABLE IF NOT EXISTS musiclogs(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), songname TEXT, songauthor TEXT, guildId INTEGER, timestamp INTEGER);

CREATE TABLE IF NOT EXISTS commandlog(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), command TEXT, guildId INTEGER, userId INTEGER, timestamp INTEGER);

CREATE TABLE IF NOT EXISTS slashcommandlog(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), command TEXT, guildId INTEGER, userId INTEGER, timestamp INTEGER, commandstring TEXT);

CREATE TABLE IF NOT EXISTS ha3users(ingamename TEXT(64) NOT NULL, realname TEXT, dcname TEXT, dcId INTEGER NOT NULL, approved INTEGER, CONSTRAINT pk PRIMARY KEY(ingamename(1024), dcId));

CREATE TABLE IF NOT EXISTS lernsaxinteractions(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), lernplanId TEXT);

CREATE TABLE IF NOT EXISTS gourmettaInteractions(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), lastday LONG);

CREATE TABLE IF NOT EXISTS githubinteractions(id INTEGER NOT NUlL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), lastcommit TEXT);

CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER NOT NULL AUTO_INCREMENT, CONSTRAINT pk PRIMARY KEY (id), type INTEGER NOT NULL, target INTEGER NOT NULL, targetDcId INTEGER NOT NULL, subscriptionId INTEGER);

CREATE TABLE IF NOT EXISTS vplandata(lesson INTEGER, room TINYTEXT);

CREATE TABLE IF NOT EXISTS userreacts(userId INTEGER NOT NULL, guildId INTEGER, messageId INTEGER NOT NULL, emote VARCHAR(255) NOT NULL, state BOOLEAN, CONSTRAINT pk PRIMARY KEY(userId, guildId, messageId, emote));
